# main:
#   allowed-circular-references: true

# spring:
#   application:
#     name: blogger

#   security:
#     oauth2:
#       client:
#         registration:
#           google:
#             client-id: 1099168239645-xxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
#             client-secret: GOCSPX-xxxxxxxxxxxxxxxxxxxxxxxxxx

#   datasource:
#     url: jdbc:postgresql://ep-rough-darkness-adfrk27t-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#     username: neondb_owner
#     password: npg_VuJ6p2WkxfhI
#     driver-class-name: org.postgresql.Driver

#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: kaif8700979251@gmail.com
#     password: debl rebv cldo hucs
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true  

#   data:
#     redis:
#       host: redis-11466.crce182.ap-south-1-1.ec2.redns.redis-cloud.com
#       port: 11466
#       username: default
#       password: TXx18KiWSPdadu5VObLxNmdxJ7Iumkiq

#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update
#     show-sql: true

#   devtools:
#     restart:
#       enabled: true
#     livereload:
#       enabled: true

# server:
#   address: localhost
#   port: 8080

# # main file
# spring:
#   profiles:
#     active: demo
#     default: demo