# # profile demo

# main:
#   allowed-circular-references: true

# spring:
#   application:
#     name: blogger
  
#   datasource:
#     url: jdbc:postgresql://host.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#     username: username
#     password: password
#     driver-class-name: org.postgresql.Driver

#   security:
#     oauth2:
#       client:
#         registration:
#           google:
#             client-id: 1099168239645-xxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
#             client-secret: GOCSPX-xxxxxxxxxxxxxxxxxxxxxxxxxx  

#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: username
#     password: password
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true  

#   data:
#      redis:
#       host: host
#       port: 11466
#       username: default
#       password: password


#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update
#     show-sql: true
  
#   devtools:
#     restart:
#       enabled: true
#     livereload:
#       enabled: true

# server:
#   address: localhost
#   port: 8080

# # main file
# spring:
#   profiles:
#     active: demo
#     default: demo